version: "3"

services:
  bot:
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "main_user"
      POSTGRES_PASSWORD: "main_pass"
      DISCORD_TOKEN: ""
      DEFAULT_PREFIX: "c!"
  pgdb:
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "main_user"
      POSTGRES_PASSWORD: "main_pass"