version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    volumes: 
      - ./services:/services/
      - ./node_modules:/node_modules/
  pgdb:
    ports:
      - '127.0.0.1:5432:5432'