version: "3"

services:
  bot:
    restart: unless-stopped
    labels: 
      live.nic0.description: "Discord bot service"
    depends_on: 
      - pgdb
  pgdb:
    image: postgres:12-alpine
    labels:
      live.nic0.description: "Postgres Database"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    expose:
      - '5432'

volumes: 
  postgres-data:
